apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: production
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      version: "2.24.0"
  values:
    persistence:
      enabled: true
      size: 5Gi
    replicas: 3
    resources:
      requests: { cpu: "100m", memory: "256Mi" }
      limits: { cpu: "500m", memory: "512Mi" }
    mariadb:
      enabled: false
    database:
      type: postgres
#    extraEnv:
#      - name: UPTIME_KUMA_DB_TYPE
#        value: "postgres"
#      - name: UPTIME_KUMA_DB_CONN
#        value: "postgresql://$(DB_USER):$(DB_PASSWORD)@uptime-kuma-postgres-prod-rw.$(NAMESPACE).svc.cluster.local:5432/$(DB_NAME)"
#      - name: DB_USER
#        valueFrom: { secretKeyRef: { name: uptime-kuma-postgres-prod-app, key: user } }
#      - name: DB_PASSWORD
#        valueFrom: { secretKeyRef: { name: uptime-kuma-postgres-prod-app, key: password } }
#      - name: DB_NAME
#        valueFrom: { secretKeyRef: { name: uptime-kuma-postgres-prod-app, key: dbname } }
#      - name: NAMESPACE
#        value: "production"
      secretName: uptime-kuma-postgres-app
      keys:
        host: host
        port: port
        database: dbname
        username: user
        password: password
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: kuma.prod.local
          paths:
            - path: /
              pathType: Prefix

