apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      version: "2.24.0"
  values:
    replicas: 1
    mariadb:
      enabled: false
    database:
      type: postgres
      secretName: uptime-kuma-postgres-app
      keys:
        host: host
        port: port
        database: dbname
        username: user
        password: password

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: kuma.staging.local
          paths:
            - path: /
              pathType: Prefix
